pipeline:
  name: Spring Harness Demo CI
  identifier: SpringHarnessDemoCI
  projectIdentifier: springharnessdemo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1762468233345   # your org/account-scoped connector
        repoName: dodtsair/spring-harness-demo                  # set once per pipeline
        # Let triggers (or manual runs) pick the ref:
        build:
          type: branch
          spec:
            branch: main  
  stages:
    - stage:
        name: Build APK and Project
        identifier: BuildApkAndProject
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Check Melange Version
                  identifier: MelangeVersionCheck
                  spec:
                    # 1. Use the Melange builder image as the base for this step
                    # docker run --privileged --rm -v "${PWD}":/work   cgr.dev/chainguard/melange version 
                    # image: cgr.dev/chainguard/melange:latest
                    command: |
                      cd packages
                      docker run --rm -v "${PWD}":/work \
                        cgr.dev/chainguard/melange keygen 
                      cd ..
                      docker run --privileged --rm -v "${PWD}":/work   cgr.dev/chainguard/melange build melange.yaml --arch amd64,aarch64 --signing-key packages/melange.rsa
              - step:
                  type: Run
                  name: Install meta-package and build project
                  identifier: InstallAndBuild
                  spec:
                    shell: Sh
                    image: cgr.dev/chainguard/wolfi-base:latest
                    command: |
                      # Trust the generated melange public key so apk can verify the package
                      cp ./packages/melange.rsa.pub /etc/apk/keys/
                      apk update || true
                      # Install the locally-built meta-package; apk will pull runtime deps from Wolfi repos
                      apk add --no-cache ./packages/x86_64/spring-harness-demo-build-deps-*.apk
                      # Make the JDK discoverable to Gradle toolchains
                      export JAVA_HOME="/usr/lib/jvm/java-21-openjdk"
                      export PATH="$JAVA_HOME/bin:$PATH"
                      java -version
                      ./gradlew --version
                      ./gradlew build
