pipeline:
  name: Spring Harness Demo CI
  identifier: SpringHarnessDemoCI
  projectIdentifier: springharnessdemo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1762468233345   # your org/account-scoped connector
        repoName: dodtsair/spring-harness-demo                  # set once per pipeline
        # Let triggers (or manual runs) pick the ref:
        build:
          type: branch
          spec:
            branch: main  
  stages:
    - stage:
        name: Build APK and Project
        identifier: BuildApkAndProject
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build meta-package with Melange
                  identifier: MelangeBuild
                  spec:
                    image: cgr.dev/chainguard/melange:latest
                    entrypoint:
                      - melange
                    args:
                      - build
                      - melange.yaml
                      - --arch
                      - x86_64
              - step:
                  type: Run
                  name: Install meta-package and build project
                  identifier: InstallAndBuild
                  spec:
                    shell: Sh
                    image: cgr.dev/chainguard/wolfi-base:latest
                    command: |
                      set -euxo pipefail
                      # Install the locally-built meta-package; apk will pull runtime deps from Wolfi repos
                      apk add --no-cache ./packages/x86_64/spring-harness-demo-build-deps-*.apk
                      ./gradlew --version
                      ./gradlew build
