pipeline:
  name: Spring Harness Demo CI
  identifier: SpringHarnessDemoCI
  projectIdentifier: springharnessdemo
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1762468233345   # your org/account-scoped connector
        repoName: dodtsair/spring-harness-demo                  # set once per pipeline
        # Let triggers (or manual runs) pick the ref:
        build:
          type: branch
          spec:
            branch: main  
  stages:
    - stage:
        name: Build Project
        identifier: BuildProject
        type: CI
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Compute image tag and ref
                  identifier: ComputeImageTag
                  spec:
                    shell: Sh
                    command: |
                      set -eu
                      if TREE=$(git rev-parse -q --verify HEAD:.harness/BuildProject 2>/dev/null); then
                        TAG=$(git rev-parse --short=16 "$TREE")
                      else
                        TAG=nohash
                      fi
                      IMAGE_REPO=$(printf "%s/%s" "<+pipeline.identifier>" "<+stage.identifier>" | tr '[:upper:]' '[:lower:]')
                      IMAGE_REF="${IMAGE_REPO}:$TAG"
                      # assign shell variables used by the Harness engine when exporting
                      CONTENT_TAG="$TAG"
                      echo "CONTENT_TAG=$TAG"
                      echo "IMAGE_REPO=$IMAGE_REPO"
                      echo "IMAGE_REF=$IMAGE_REF"
                      # export for Harness output variables
                      echo "export CONTENT_TAG=$CONTENT_TAG"
                      echo "export IMAGE_REPO=$IMAGE_REPO"
                      echo "export IMAGE_REF=$IMAGE_REF"
                    outputVariables:
                      - name: CONTENT_TAG
                      - name: IMAGE_REPO
                      - name: IMAGE_REF
              - step:
                  type: Run
                  name: Detect melange config
                  identifier: DetectMelange
                  spec:
                    shell: Sh
                    command: |
                      set -eu
                      if [ -f .harness/BuildProject/melange.yaml ]; then
                        MELANGE_PRESENT=1
                      else
                        MELANGE_PRESENT=0
                      fi
                      export MELANGE_PRESENT
                      echo "export MELANGE_PRESENT=$MELANGE_PRESENT"
                    outputVariables:
                      - name: MELANGE_PRESENT
              - step:
                  type: Run
                  name: Check if image exists
                  identifier: CheckImageExists
                  spec:
                    shell: Sh
                    command: |
                      set -eu
                      IMAGE_REF="<+execution.steps.ComputeImageTag.output.outputVariables.IMAGE_REF>"
                      echo "Probing image: $IMAGE_REF"
                      if docker manifest inspect "$IMAGE_REF" >/dev/null 2>&1; then
                        IMAGE_EXISTS=1
                      else
                        IMAGE_EXISTS=0
                      fi
                      export IMAGE_EXISTS
                      echo "export IMAGE_EXISTS=$IMAGE_EXISTS"
                    outputVariables:
                      - name: IMAGE_EXISTS
              - step:
                  type: Run
                  name: Conditional Melange build
                  identifier: ConditionalMelangeBuild
                  when:
                    stageStatus: Success
                    condition: "<+execution.steps.DetectMelange.output.outputVariables.MELANGE_PRESENT> == \"1\" && <+execution.steps.CheckImageExists.output.outputVariables.IMAGE_EXISTS> == \"0\""
                  spec:
                    shell: Sh
                    command: |
                      set -eu
                      if [ -f .harness/BuildProject/melange.yaml ]; then
                        echo "melange.yaml found; building APKs"
                        cd .harness/BuildProject/
                        docker run --rm -v "${PWD}":/work \
                          cgr.dev/chainguard/melange keygen
                        docker run --privileged --rm -v "${PWD}":/work \
                          cgr.dev/chainguard/melange build melange.yaml \
                          --arch amd64,aarch64 \
                          --signing-key ./melange.rsa
                        cd - >/dev/null 2>&1 || true
                      else
                        echo "No melange.yaml found at .harness/BuildProject/melange.yaml; skipping APK build"
                      fi
              - step:
                  type: Run
                  name: Create Dockerfile for build image
                  identifier: CreateDockerfile
                  when:
                    stageStatus: Success
                    condition: "<+execution.steps.DetectMelange.output.outputVariables.MELANGE_PRESENT> == \"1\" && <+execution.steps.CheckImageExists.output.outputVariables.IMAGE_EXISTS> == \"0\""
                  spec:
                    shell: Sh
                    command: |
                      set -eu
                      cat > .harness/BuildProject/Dockerfile <<'EOF'
                      FROM cgr.dev/chainguard/wolfi-base:latest
                      WORKDIR /app
                      COPY packages /app/packages
                      RUN apk update || true && \
                          # trust local key if present
                          if [ -f /app/packages/melange.rsa.pub ]; then cp /app/packages/melange.rsa.pub /etc/apk/keys/; fi && \
                          # install build deps meta-package if present
                          if ls /app/packages/x86_64/spring-harness-demo-build-deps-*.apk >/dev/null 2>&1; then \
                            apk add --no-cache /app/packages/x86_64/spring-harness-demo-build-deps-*.apk; \
                          fi && \
                          rm -rf /var/cache/apk/*
                      EOF
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push build image
                  identifier: BuildAndPushImage
                  when:
                    stageStatus: Success
                    condition: "<+execution.steps.DetectMelange.output.outputVariables.MELANGE_PRESENT> == \"1\" && <+execution.steps.CheckImageExists.output.outputVariables.IMAGE_EXISTS> == \"0\""
                  spec:
                    connectorRef: hamishesdockerhub
                    repo: <+execution.steps.ComputeImageTag.output.outputVariables.IMAGE_REPO>
                    tags:
                      - <+execution.steps.ComputeImageTag.output.outputVariables.CONTENT_TAG>
                    dockerfile: .harness/BuildProject/Dockerfile
                    context: .
              - step:
                  type: Run
                  name: Compute image to use
                  identifier: ComputeImageToUse
                  spec:
                    shell: Sh
                    command: |
                      set -eu
                      if [ "<+execution.steps.DetectMelange.output.outputVariables.MELANGE_PRESENT>" = "1" ]; then
                        IMAGE_TO_USE="<+execution.steps.ComputeImageTag.output.outputVariables.IMAGE_REPO>:<+execution.steps.ComputeImageTag.output.outputVariables.CONTENT_TAG>"
                      else
                        IMAGE_TO_USE="cgr.dev/chainguard/wolfi-base:latest"
                      fi
                      echo "Using image: $IMAGE_TO_USE"
                      export IMAGE_TO_USE
                      echo "export IMAGE_TO_USE=$IMAGE_TO_USE"
                    outputVariables:
                      - name: IMAGE_TO_USE
              - step:
                  type: Run
                  name: Install meta-package and build project
                  identifier: InstallAndBuild
                  spec:
                    shell: Sh
                    image: <+execution.steps.ComputeImageToUse.output.outputVariables.IMAGE_TO_USE>
                    command: |
                      # Make the JDK discoverable to Gradle toolchains
                      export JAVA_HOME="/usr/lib/jvm/java-21-openjdk"
                      export PATH="$JAVA_HOME/bin:$PATH"
                      echo "JAVA_HOME=$JAVA_HOME"
                      which java || true
                      which javac || true
                      java -version
                      javac -version || true
                      ./gradlew --version || true
                      ./gradlew build
