# build-image/BUCK
# Depend on the APK files from the melange target
genrule(
    name = "build-image",
    out = "spring-harness-demo.tar",
    cmd = """      
        mkdir -p $OUT  
        # Copy the APK files to the build context
        cp -r $(location //melange:apk-files)/* $TMP/
        
        # Copy the Dockerfile to the output directory
        cp $(source kaniko-workspace/Dockerfile) $TMP/Dockerfile
        
        # Build the Docker image
        (cd $TMP && docker build -t spring-harness-demo:latest .)
        

        echo here
        echo $OUT
        echo here2
        # Save the image to a tar file
        docker save -o $OUT/spring-harness-demo.tar spring-harness-demo:latest
    """,
    visibility = ["//..."],
)

# # Export the built image
# export_file(
#     name = "image",
#     src = ":build-image",
#     out = "spring-harness-demo-image",
#     visibility = ["//..."],
# )

genrule(
    name = "build-kaniko-image",
    out = "spring-harness-demo.tar",
    cmd = """      
        
        # Run Kaniko to build and save the image
        docker run --rm \
            -v "$(source kaniko-workspace):/workspace" \
            -v "$(location //melange:apk-files):/workspace/apk-files" \
            -v "$OUT:/output" \
            gcr.io/kaniko-project/executor:latest \
            --dockerfile=/workspace/Dockerfile \
            --context=dir:///workspace \
            --destination=spring-harness-demo:latest \
            --tarPath=/output/spring-harness-demo.tar \
            --no-push
        docker load -i $OUT/spring-harness-demo.tar
        docker tag spring-harness-demo:latest spring-harness-demo:latest    
    """,
    visibility = ["//..."],
)