# Image BUCK file
load("@prelude//container:container.bzl", "container_image")

container_image(
    name = "spring-harness-demo-image",
    base = "//melange:java-runtime",
    layers = [
        "//java-app:spring-harness-demo",
    ],
    entrypoint = ["/app/spring-harness-demo"],
    visibility = ["PUBLIC"],
)
